### ISSUE TITLE
WHATIF - orders

### ISSUE THREAD

**Issue by Despair2000** [softwarespartan/IB4m#104]
I want to find the margin requirement for different option spreads and want to do this by placing a WHATIF orders.

The API-documentation says the results of such a query is returned as IBApi.OrderState object but I'm wondering where do I find this object? I checked for open order, order status and exec details events but all buffers remain empty.

@softwarespartan can you maybe tell me where the result ends up?

**Comment by Despair2000** [comment]
@softwarespartan When you look at reqSecDefOptParam can you maybe also have a look at this one. Would be highly appreciated.

**Comment by softwarespartan** [comment]
OK, will do.  Thanks for bumping this

**Comment by softwarespartan** [comment]
Do you have example for how you're placing the `whatif` order?

**Comment by softwarespartan** [comment]
The `OrderState` object comes in from the `OpenOrder` events
```
case 'com.tws.Handler$OpenOrderEvent'        
    notify(                                    ...
       TWS.Events.getInstance()              , ...
        TWS.Events.OPENORDER                 , ...
        TWS.EventData.OpenOrder(event)         ...
    );
```

which contains an OpenOrder with 

```
public class OpenOrder {

    public final int        orderId   ;
    public final Contract   contract  ;
    public final Order      order     ;
    public final OrderState orderState;

```

OrderStatus callback is also implemented.

**Comment by Despair2000** [comment]
I don't. I will try it today during the afternoon. Maybe it's working and the results end up as OpenOrder event.

**Comment by Despair2000** [comment]
I tested it and it works perfectly.

I just didn't understand that the data would generate an openOrder event (although it said so in the documentation). Thanks for pointing this out.

I close the issue.

**Comment by softwarespartan** [comment]
Excellent
