### ISSUE TITLE
Compiling TWS973 - Unrecognized function or variable 'getEventWithRemove'

### ISSUE THREAD

**Issue by quebien90** [softwarespartan/IB4m#106]
Dear Softwarespartan,
I have been using your Matlab API for some weeks now and it is working perfectly fine. Thank you a lot for this great work, really appreciate it. 
I was hoping you can help me to recompile the .jar. 
Currently I am trying to expand the functionality, the reqScannerParameters as example. For starters, I just want to be able to recompile the original .jar. From there I should be able to add reqScannerParameters callbakcs / events by myself.
So far I have:
Read the related issues "[Learning on how to expose additional TWS API Events](https://github.com/softwarespartan/IB4m/issues/39)" and "[Getting results from scannerParameters](https://github.com/softwarespartan/IB4m/issues/48)". 
Installed Eclipse, installed Java **1.8.0_101**, chose compilance **level 1.7** while using the installed 1.8 compiler.
Added to Build Path: /Applications/**MATLAB_R2020a**/java/jar/jmi.jar
Succesfully compiled TWS973.jar. 
Added the new .jar to matlab javapath with javaaddpath as in your tutorials.
When trying to open a session I gett following Matlab error:
```
Unrecognized function or variable 'getEventWithRemove'.
Error in TWS.processNotification (line 4)
    event = n.getSource().getEventWithRemove(n.uuid); 
com.mathworks.jmi.MatlabException: Undefined function 'getEventWithRemove' for input arguments of type 'com.tws.Handler'.
	at com.mathworks.jmi.NativeMatlab.SendMatlabMessage(Native Method)
	at com.mathworks.jmi.NativeMatlab.sendMatlabMessage(NativeMatlab.java:273)
	at com.mathworks.jmi.MatlabLooper.sendMatlabMessage(MatlabLooper.java:120)
	at com.mathworks.jmi.Matlab.mtFevalConsoleOutput(Matlab.java:1835)
	at com.proxy.ProxyBuilder$Handler$2.run(ProxyBuilder.java:125)
```
The Java project has no errors but 41 Warnings. I attached them as .png. I assume it is the matlab - java - version problem you mentioned in issue [#39](https://github.com/softwarespartan/IB4m/issues/39) but I thought I already took the necessary measures? I would be very happy if you found time to help me resolving this issue, as I am not very versatile in java.

Kind regards,
Kevin

![javaWarnings](https://user-images.githubusercontent.com/72934365/96155094-d1941100-0f0f-11eb-8a8f-af657f51f75a.PNG)

**Comment by Despair2000** [comment]
I'm worthless regarding java but I think you might try to compile the wrong version of the Jar-file. The function 'getEventWithRemove' @softwarespartan added quite recently to resolve a problem.

**Comment by quebien90** [comment]
Thanks for the reply. Yes, that would explain it. Handler.java class does not have the `getEventWithRemove`, only `getEvent`. I could add it myself or adapt `TWS.processNotification`. However, the source code was updated 2 years ago and I imagine more changes have been done since then. 
In that case, I would be grateful getting access to an updated source code. @softwarespartan, is this anyhow possible :) ?

**Comment by softwarespartan** [comment]
@quebien90 I've updated the TWS973 src code.  Sorry, I had forgotten to push java src updates along with updated jar file.  Let me know if that works.  BTW, check the compiler version in your Matlab and make sure you do not exceed that version.  If compile the jar with version ahead of what is in Matlab, the class loader will just simply (and silently!) ignore those class files when adding them to the matlab java path.  I typically compile that jar with jdk1.8.0_101 so that it is compatible with older versions of matlab (i.e. the java version in older matlab).  Newer matlab java is always backwards jdk compatible so works out fine.

**Comment by quebien90** [comment]
@softwarespartan 
Thank you very much, this did the trick! Compilation works, Matlab communicates with TWS through the new .jar. 
I used jdk1.8.0_101 as well. 
My Matlab2020a has `>> ver('compiler') = 8.0`
Note: I had to `>> clear java` after replacing the .jar and before adding it to the path.

Kind regards
Kevin
