### ISSUE TITLE
reqSecDefOptParam

### ISSUE THREAD

**Issue by Despair2000** [softwarespartan/IB4m#108]
I'd like to use reqSecDefOptParam to download whole option chains. Using the contract details to do so is painfully slow and also not recommended according to the API documentation.
@softwarespartan do I understand right that the event has to be exposed first to use this method?

**Comment by softwarespartan** [comment]
yes, that's correct.  Needs to be exposed.

https://interactivebrokers.github.io/tws-api/options.html

```
public void securityDefinitionOptionParameter(
    int reqId, 
    string exchange, 
    int underlyingConId, 
    string tradingClass, 
    string multiplier, 
    HashSet<string> expirations, 
    HashSet<double> strikes
)
```

I'll try to get it wired up this week sometime.

**Comment by softwarespartan** [comment]
Update pushed for `reqSecDefOptParam`.  Let me know if find any bugs.  Will start on `whatif` next

**Comment by Despair2000** [comment]
@softwarespartan Is the events.m correct? You didn't add any event.

**Comment by softwarespartan** [comment]
Yes, that’s correct.

I should have mentioned that.  

I configured the option parameters to come in via the contract details event.  Just trying to be sensible about how many different event type there are.  Since this call is really just to speed up what would normally be a contract details call any way.  

This can be easily changed.  if prefer separate event type that’s no problem.

**Comment by Despair2000** [comment]
OK, great. Sounds reasonable. I will test the new function this weekend and let you know if anything looks strange.

**Comment by Despair2000** [comment]
I tested the function and it works as advertised after correcting a little typo you had in the events.m.
The class(event) should be 'com.tws.Handler$OptionParameterEvent' and not 'com.tws.OptionParameter'. You maybe want to correct this.
Otherwise thanks  for exposing this function, this will be very useful!

Have a great weekend!

**Comment by Despair2000** [comment]
I close also this issue since it is done. @softwarespartan Just make sure you correct the typo I mentioned above before somebody else finds it :-P
