### ISSUE TITLE
historicalDataEnd 

### ISSUE THREAD

**Issue by bondtrade** [softwarespartan/IB4m#112]
Hi Abel,
Can we monitor for this event rather than waiting around for a nominal amount of time to check if a buffer has been populated?
It becomes compelling when iterating through a large symbol list...
Thank you.

**Comment by softwarespartan** [comment]
I think so, yes.  Currently it’s used internally to figure out when to fire event for historical data.  I can expose.

**Comment by bondtrade** [comment]
Ok. So if put a listener on HISTORICALDATA that will achieve the same thing?

**Comment by softwarespartan** [comment]
yes, exactly.  That would be the recommended solution

**Comment by bondtrade** [comment]
Will do. Thanks again.
