### ISSUE TITLE
reqHistoricalData error with certain symbols

### ISSUE THREAD

**Issue by ajdore** [softwarespartan/IB4m#113]
Having an error with SPY when I run the historical data demo code (other symbols work fine).

                      % create an empty stock contract
                      contract = com.ib.client.Contract();
                      contract.symbol('SPY')
                      contract.exchange('SMART');
                      contract.primaryExch('ARCA');
                      contract.currency('USD');
                      contract.secType('STK');

                        % request historical data for our contract for a year w/ 1-day bars
                        session.eClientSocket.reqHistoricalData(1000001,contract,'20141230 16:00:00','1 Y','1 day','TRADES',1,1,false,[]); pause(0.5);

returns this error
                      
                      1000001 162 Historical Market Data Service error message:Delayed market data query for ARCA STK
                      
                      Error using HistoricalDataExample (line 37)
                      Java exception occurred:
                      org.apache.commons.collections.BufferUnderflowException: The buffer is already empty
                      
	                      at org.apache.commons.collections.buffer.BoundedFifoBuffer.get(BoundedFifoBuffer.java:261)

However, the same request for AGG returns fine (AGG has the same contract details as SPY).

**Comment by ajdore** [comment]
Looks like the issue was related to data limitations on the IB end.

**Comment by softwarespartan** [comment]
The exception is related to calling get method when the buffer is empty.  It’s not very idiomatic of matlab to do that so it generally confuses everyone.  The easy work around is to just check if buf.size > 0 then e=buf.get()
