### ISSUE TITLE
Market Data example

### ISSUE THREAD

**Issue by ajdore** [softwarespartan/IB4m#117]
When I try to run the market data example, I get this error:

```
No public field m_exchange exists for class com.ib.client.Contract.

Error in MarketDataExample (line 82)
contract.m_exchange = 'ARCA';  contract.m_primaryExch = 'ARCA';
```

Is there any updated example?

I've tried to clean up the code but have had no luck.  Dont know Java that well.  A similar issues seems to be documented here: https://github.com/softwarespartan/IB4m/issues/44

**Comment by softwarespartan** [comment]
Apologies for confusion.  The code you've posted is from the older version of the IB API.  The +9.72 api made changes to how contracts etc were defined which broke the API compatibility (their choice not mine :)

The current code has been updated for these API changes but ... looks, there was a straggler line that needs updated for new contract definition (see lines 56-57).

```
contract.exchange('ARCA');  contract.primaryExch('ARCA');
```

The docs for defining contracts are here

https://interactivebrokers.github.io/tws-api/basic_contracts.html
