### ISSUE TITLE
Getting PnL (Profit-and-Loss) data

### ISSUE THREAD

**Issue by beppe969** [softwarespartan/IB4m#120]
Hello, is there an example in the documentation for getting PnL data?
What I need to do is to obtain the current Profit-and-Loss data (both realized and unrealized) for my account.

I see there are  client.reqPnLSingle and client.reqPnL requests in the TWS API, but I can't find instructions for their use in IB4m.

Thanks in advance for your help!

Giuseppe

**Comment by Despair2000** [comment]
If you subscribe to account updates you receive the unrealized pnl for all your positions every 3 minutes.

The realized pnl of a closed position you receive with the commissions report that follows when you request execution details. This is available for positions closed within the last 24h. Longer history you can't get via the API so you have to do some book keeping yourself.

The events for reqPnLSingle and reqPnL are not exposed yet so they won't work with IB4m yet. You would have to ask @softwarespartan to add them if you feel that you need them.

**Comment by softwarespartan** [comment]
I can expose them if needed.  Let me know

**Comment by beppe969** [comment]
Dear Abel

Sure, it will be very useful to be able to get real-time realized and unrealized performance of the current portfolio. Thanks in advance for your help!

Best,
Giuseppe

**Comment by giovannetti87** [comment]
Hi Abel,

Following Giuseppe, I would be extremely grateful if you can expose the PnL. 

Thanks a lot!

**Comment by giovannetti87** [comment]
Hi @softwarespartan , apologies if I didn't tagged you in the previous message. It would be great to have the PnL function for us to include in our scripts, in case you don't mind doing one.

thanks a lot,
andrea

**Comment by softwarespartan** [comment]
@beppe969 @Despair2000 @giovannetti87 

PNL events have been added.  Let me know if find any bugs.

**Comment by giovannetti87** [comment]
Legend! I will add it next days and report back,
thanks,
