### ISSUE TITLE
Modifying orders

### ISSUE THREAD

**Issue by bondtrade** [softwarespartan/IB4m#122]
Hi Abel,

Are you able to provide guidance with modifying orders please: both those placed through the API and manually into TWS?

Your framework supports the reqAllOpenOrders() method but not the reqOpenOrders() method (I don't think) which I think is required to bind to orders placed manually in TWS.

**Comment by Despair2000** [comment]
To modify an existing order simply resubmit it with the same orderId like the original order.

If this is also possible for manually placed orders I don't know.
