### ISSUE TITLE
Callback

### ISSUE THREAD

**Issue by achille1112** [softwarespartan/IB4m#125]
Dear Abel,
thanks for working on this Matlab IB API.
When I place an order can I attach an Order Status Callback?

Best Regards.
Domenico.

**Comment by softwarespartan** [comment]
Thanks for reaching out.

Yes, you certainly can get order status.

The event is `TWS.Events.TWS_ORDERSTATUS`

There is an example in `IB4m/docs/OpenOrdersExample.m`

**Comment by achille1112** [comment]
Thank you very much Abel!

Best Regards. 
Domenico
