### ISSUE TITLE
Positions request

### ISSUE THREAD

**Issue by achille1112** [softwarespartan/IB4m#130]
Dear Abel,
I have a problem when I request my positions via API using the following code:

```
% initialize session with TWS
session = TWS.Session.getInstance();

% create local buffer for Positions data events 
[bufP,lhP] = TWS.initBufferForEvent({
    TWS.Events.POSITIONS,...
    });

% connect to TWS
session.eClientSocket.eConnect('127.0.0.1',7496,0); pause(1)

session.eClientSocket.reqPositions(); pause(0.5)

hde = bufP.get();
```

I obtain the following error:

```
Java exception occurred:
org.apache.commons.collections.BufferUnderflowException: The buffer is already empty

	at org.apache.commons.collections.buffer.BoundedFifoBuffer.get(BoundedFifoBuffer.java:261)
```

Even if I wait several seconds I always get the same error.

Could you help me to understand why this happens?

Best Regards.
Domenico.

**Comment by softwarespartan** [comment]
It just means the buffer was empty.  Here if call “get” on empty buffer then an exception is thrown.  Can just do “if buf.size()>0; e=buf.get(); end

**Comment by achille1112** [comment]
Ok, thank you very much for your answer.
The buffer is empty when there is not open positions?

Best regards.
Domenico

**Comment by Despair2000** [comment]
If there are no open positions the request doesn't return anything so the buffer remains empty. But even if there are positions it can sometimes take 1-2s for them to show up in the buffer so it can be a good idea to implement a loop that waits for something to drop in the buffer.
This is true also for other requests. Especially if you have a fast computer you often have to wait for the answer of the API.

**Comment by achille1112** [comment]
Thanks Despair2000!
But even if I wait few minutes I obtain the same error.

Best regards.
Domenico

**Comment by Despair2000** [comment]
And you have open positions?

Minutes it should definitely not take.

**Comment by achille1112** [comment]
When there are not open positions I obtain the error indipendently from the seconds that I wait.

Best regards
Domenico

**Comment by Despair2000** [comment]
Ok, and what happens if there is an open position?

**Comment by achille1112** [comment]
If there is an open position at the start of the session I obtain no error.

Best regards
Domenico

**Comment by Despair2000** [comment]
Sounds like all works fine. A closed position is often still returned but with positionSize 0.

**Comment by achille1112** [comment]
Ok thanks Despair2000!
Then if I open a position and after I close the position I obtain no error because the position is with positionSize=0.
If there is no open position at the start of the session I obtain the error because there is no position in the buffer.

Is that right or did I get it wrong?

Best regards
Domenico


Best regards.
Domenico.

**Comment by Despair2000** [comment]
When create the buffer it is obviously empty.
When you request the open positions while there is a position the request returns this position to the buffer.
When you close the position the same position is still returned on request with size 0.

You should see that if you look at the returned data.

**Comment by achille1112** [comment]
Thank you very much Despair!

Best Regards
Domenico
