### ISSUE TITLE
Strange java error

### ISSUE THREAD

**Issue by Despair2000** [softwarespartan/IB4m#133]
Today suddenly the following error popped up in my command window. My program didn't seem to mind and kept on going. I wanted to report it anyway.

![error](https://user-images.githubusercontent.com/38463411/127048680-f06264a9-9af2-47d8-9697-3c8bcdf8fa50.PNG)

**Comment by softwarespartan** [comment]
I get msgs like this sometimes as well when I have other code dev tools open on my computer like intelij etc.  Something to do with the class loader but like you I've never had problem materialize as result.  Let me know if becomes issue.
