### ISSUE TITLE
Time and Sales

### ISSUE THREAD

**Issue by dalefin** [softwarespartan/IB4m#141]
Hi!

First, thank you so much for providing IB4m - it helps a ton!

I have a question.
How am I able to import historical Time&Sales data of a specific timeframe.
Historical Bar Data I was able to get.
But do you also have a function or script for Time & Sales?

Thanks again, you guys are great!
dalefin

**Comment by softwarespartan** [comment]
Thanks for reaching out.  

The api calls should be here

https://interactivebrokers.github.io/tws-api/historical_time_and_sales.html

Let me know if any issues 

-abel
