### ISSUE TITLE
reqContractDetails not working for options

### ISSUE THREAD

**Issue by PapeJ12** [softwarespartan/IB4m#147]
The example __OptionsComputationsIB4m__ dosn't work properly.
The variable `detailsBuf `remains empty after trying to get the option details with `session.eClientSocket.reqContractDetails(0,contract);`

Here is the code that has porblems:
### Code
```
clear all;
clc;
path = 'C:\*******\MATLAB_WD\github_repo\'; %personal folder
addpath(path);
addpath(fullfile(path,'docs'));
javaaddpath(fullfile(path,'Jar','TWS973.jar'));

% configure buffers for contract details, market data, and options computations
[detailsBuf ,detailslh] = TWS.initBufferForEvent(TWS.Events.CONTRACTDETAILS  );
[   dataBuf ,   datalh] = TWS.initBufferForEvent(TWS.Events.MARKETDATA       ,10000);
[    optBuf ,    optlh] = TWS.initBufferForEvent(TWS.Events.OPTIONCOMPUTATION,10000);

% initialize session with TWS
session = TWS.Session.getInstance();

% connect to TWS
session.eClientSocket.eConnect('127.0.0.1',7496,0);

% create contract object
contract = com.ib.client.Contract();
contract.symbol('SPX')
contract.primaryExch([]);
contract.currency('USD');
contract.secType('OPT');

% get all the details for this option
session.eClientSocket.reqContractDetails(0,contract); pause(2)

% turn hashset into cell array
e = collection2cell(detailsBuf.get().data);
```

### Error:
```
Java exception occurred:
org.apache.commons.collections.BufferUnderflowException: The buffer is already empty

	at org.apache.commons.collections.buffer.BoundedFifoBuffer.get(BoundedFifoBuffer.java:261)
```
Can anybody help? Thank you very much!
Davide

**Comment by Despair2000** [comment]
Try again in a few hours or tomorrow. It is common that the API doesn't respond as it should on Saturdays. IB is running maintenance on their server.
Sometimes it works and sometimes it does not. I tried it myself a few minutes ago and couldn't get any data either.

**Comment by PapeJ12** [comment]
Hi @Despair2000, thanks for the feedback.
I already known about the API issues on Saturdays. I asked only because with STK type it works everytime. 
Anyway, I'll try again when markets are open.
Thanks!
P.S.
I’ve been using these functions since today, so I thought there might be other problems. Sorry for the dumb question.
