### ISSUE TITLE
IB Algo Adaptive

### ISSUE THREAD

**Issue by manishranjan99** [softwarespartan/IB4m#23]
Dear Abel,

Do you have an example on how to implement the IB TWS algo with the TWS?  I guess specifying the algo strategy is straight forward, however, I am confused on how to create the list to add the algo parameteres.  I would appreciate any help with this.
https://interactivebrokers.github.io/tws-api/ibalgos.html

Kind Regards,
Manish

**Comment by softwarespartan** [comment]
Hi Manish

Great to hear from you.

You should be able to just fill out the associated fields of the order "m_algoStrategy" and "m_algoParams" where the algoParams is actually a java.util.Vector of TagValue objects.

For example:
`order = com.ib.client.Order()`
`order.m_algoStrategy = 'Adaptive'`
`params = java.util.Vector()`
`tagValue = com.ib.client.TagValue('adaptivePriority', 'Normal')`
`params.add(tagValue)`
`order.m_algoParams = params`

Let me know if you need anything additional.

Cheers
-abel

**Comment by manishranjan99** [comment]
Hi Abel,

This looks great! Thank you so much!  

Manish
