### ISSUE TITLE
Couldn't Connect to TWS

### ISSUE THREAD

**Issue by trippingCub** [softwarespartan/IB4m#27]
I'm stuck at the very start, with Matlab R2017b showing this error:

> -1 502 Couldn't connect to TWS.  Confirm that "Enable ActiveX and Socket Clients" is enabled on the TWS "Configure->API" menu.

I did everything mentioned in quick start, my matlab commant statements are:

```
cd 'softwarespartan-IB4m-15bb4fd';
addpath(path,pwd);
addpath(path,fullfile(pwd,'docs'))
javaaddpath(fullfile(pwd,'Jar','TWS.jar'))

AccountSummaryExample
```

I have navigated to IBM4 folder.  And I configured TWS as required. 

![image](https://user-images.githubusercontent.com/39677386/40589193-dc702428-6206-11e8-96bf-4236e5abcfb5.png)

Can you please point what I'm doing wrong here?
Appreciate your support.

**Comment by softwarespartan** [comment]
Thanks for reaching out.

Can you share the command you’re using to connect ?  This is the “session.eConnect” api call in the example you referenced. 

My initial guess is that the port provided in your connect call doesn’t match the port listed in your TWS config screen.  

Cheers
-abel

**Comment by trippingCub** [comment]
Abel,

Thanks for your fast response. I found this is `AccountSummaryExample` file:
```
% establish connection with TWS
session.eClientSocket.eConnect('127.0.0.1',7496,0);
```
The port numbers are different. Which one should I change? The one in the code?

**Comment by trippingCub** [comment]
I changed the port number in the `AccountSummaryExample` file, it was a succes but then showed this error:

> Error using AccountSummaryExample (line 56)
> Java exception occurred:
> org.apache.commons.collections.BufferUnderflowException: The buffer is already empty
> 
> 	at org.apache.commons.collections.buffer.BoundedFifoBuffer.get(BoundedFifoBuffer.java:260)

**Comment by softwarespartan** [comment]
It just means the queue is empty . Some times it can take longer for TWS to
reply so pause for longer

-abel

**Comment by trippingCub** [comment]
Thank you, everything works as it should now!
