### ISSUE TITLE
Unable to connect to TWS

### ISSUE THREAD

**Issue by Jdo503** [softwarespartan/IB4m#31]
Hi,

I am trying to connect to TWS and run the Account Summary but I get the following error….

**-1 502 Couldn't connect to TWS.  Confirm that "Enable ActiveX and Socket Clients" is enabled on the TWS "Configure->API" menu.

-1 504 Not connected**

I have followed all the instructions + Enabled ActiveX and Socket Clients on TWS.....

Any ideas please?

**Comment by softwarespartan** [comment]
Thanks for reaching out.

Can you provide additional details ...

Port number in TWS api configuration  vs port number specified in the connection call is often mismatch.  Please confirm match

What is OS?

What ver of matlab?

Do you have trading toolbox installed?

**Comment by Jdo503** [comment]
Hi,

Sorry I have been on holiday. 

Yes I have been able to resolve it - It was a port number issue.....

Thanks,

J

**Comment by Despair2000** [comment]
Sorry for resurrecting this thread.

I have updated to your 9.73 version and try to make it work. One thing that feels strange and you are maybe not aware of is the following problem:
When I start the gateway and afterwards matlab, it works fine but if I then exit the gateway and restart it I receive the same error message like Jdo503. I have to close matlab and restart this also to make it work again. No big deal but I thought you might want to know.

**Comment by softwarespartan** [comment]
hm … yes indeed, I would want to know :)  Thanks for the heads up.

This could be an issue with internal thread that has to get started when connecting to TWS.  This was a poor design decision from IB but not much we can do about it.

If TWS closes then the socket gets interrupted so the thread might get clobbered.  I can double check.

Can you try “clear all” on the matlab side?  This should eject the current eclient.Reader and force JVM to make a new one when TWS.Session is created. 

-abel

**Comment by SyedShayaan** [comment]
Hi, I am also facing a similar issue where I get the error "Error  1   504   Not connected"
System Info:
Windows 10 
64 bit
Python 3.7.3  (anaconda) 
The code is mainly from IB tutorials.

from  ibapi.client import EClient 
from ibapi.wrapper import EWrapper 
from ibapi.contract import Contract 

class TestApp(EWrapper,EClient):
    def __init__(self):
        EClient.__init__(self,self)
    def error(self, reqId , errorCode, errorString):
        print("Error ", reqId, " " , errorCode, " " ,errorString)
    def historicalData(self, reqId, bar):
        print("hISTORICAL DATAa", reqId, "Date", bar.date, "openn", bar.open , "high", bar.high , "low", bar.low)
    
def main():
    app = TestApp()
    app.connect = ("127.0.0.1" , 7497,0)
    
    contract = Contract()
    contract.symbol = "EUR"
    contract.secType = "CASH"
    contract.exchange = "IDEALPRO"
    contract.currency = "USD"
  

    app.reqHistoricalData(1, contract, "","1 D", "1 min", "MIDPOINT", 0, 1, False, [])
    
    app.run()

if __name__ == "__main__":
    main()

and I have checked  Enabled ActiveX and Socket Clients on TWS and have confirmed that the port is also correct.

Any help will be appreciated.

Thanks

**Comment by softwarespartan** [comment]
Thanks for reaching out.  This repository is for IB4m.  If you have IB4m related question, happy to help.  You might post your question on Stackoverflow or similar for IB support.

**Comment by csselo** [comment]
I have the same problem

ERROR -1 502 Couldn't connect to TWS. Confirm that "Enable ActiveX and Socket EClients" 
is enabled and connection port is the same as "Socket Port" on the 
TWS "Edit->Global Configuration...->API->Settings" menu. Live Trading ports: 
TWS: 7496; IB Gateway: 4001. Simulated Trading ports for new installations 
of version 954.1 or newer:  TWS: 7497; IB Gateway: 4002
error {'args': (-1, 502, 'Couldn\'t connect to TWS. Confirm that "Enable ActiveX and Socket EClients" \nis enabled and connection port is the same as "Socket Port" on the \nTWS "Edit->Global Configuration...->API->Settings" menu. Live Trading ports: \nTWS: 7496; IB Gateway: 4001. Simulated Trading ports for new installations \nof version 954.1 or newer:  TWS: 7497; IB Gateway: 4002'), 'self': <__main__.TestApp object at 0x7f7a105c8a90>, '__class__': <class '__main__.TestApp'>}

**Comment by softwarespartan** [comment]
@csselo please confirm the port number specified in the eClient.connect call matches the port number configured in TWS.  Probably 9.9 out of 10 times, just need to specify/align the correct ports.

**Comment by harrodschui** [comment]
Hi, I also got the same error 502. 

My port number in TWS and eClient.connect call are matched.. Is there any other solution to solve this problem? 

I tried port numbers: 7496, 7497, 4002, 4001 ...still failed to connect.

Note: Tried turning-off firewall, enabled Active X....etc. still not working.

**Comment by softwarespartan** [comment]
Thanks for reaching out

Can you share the output on the command window and the command you’re running 

Also do you have trading toolbox installed?

**Comment by harrodschui** [comment]
Hi @softwarespartan , here is my command and output:
**Code:**:
`from ibapi import wrapper
from ibapi.client import EClient
from ibapi.utils import iswrapper #just for decorator
from ibapi.common import *

class TestApp(wrapper.EWrapper, EClient):
    def __init__(self):
        wrapper.EWrapper.__init__(self)
        EClient.__init__(self, wrapper=self)

    @iswrapper
    def nextValidId(self, orderId:int):
        print("setting nextValidOrderId: %d", orderId)
        self.nextValidOrderId = orderId
        # here is where you start using api
        self.reqAccountSummary(9002, "All", "$LEDGER")

    @iswrapper
    def error(self, reqId:TickerId, errorCode:int, errorString:str):
        print("Error. Id: " , reqId, " Code: " , errorCode , " Msg: " , errorString)

    @iswrapper
    def accountSummary(self, reqId:int, account:str, tag:str, value:str, currency:str):
        print("Acct Summary. ReqId:" , reqId , "Acct:", account,
            "Tag: ", tag, "Value:", value, "Currency:", currency)

    @iswrapper
    def accountSummaryEnd(self, reqId:int):
        print("AccountSummaryEnd. Req Id: ", reqId)
        # now we can disconnect
        self.disconnect()

def main():
    app = TestApp()
    app.connect("127.0.0.1", 7496, clientId=123)
    app.run()

if __name__ == "__main__":
    main()`
-----------------------------------------------------------------
![IB](https://user-images.githubusercontent.com/54462300/81769043-2e2d7300-950f-11ea-96a9-791f37ef38ba.PNG)
-------------------------------------------------------------------
**Output:** 
Error. Id:  -1  Code:  502  Msg:  Couldn't connect to TWS. Confirm that "Enable ActiveX and Socket EClients" 
is enabled and connection port is the same as "Socket Port" on the 
TWS "Edit->Global Configuration...->API->Settings" menu. Live Trading ports: 
TWS: 7496; IB Gateway: 4001. Simulated Trading ports for new installations 
of version 954.1 or newer:  TWS: 7497; IB Gateway: 4002

Process finished with exit code 0

P.S. I haven't installed trading toolbox

**Comment by softwarespartan** [comment]
@harrodschui 

Your code does not look like IB4m matlab code :) 

Looks like you're using Interactive Brokers Python API.
