### ISSUE TITLE
Buffer remains empty?

### ISSUE THREAD

**Issue by Despair2000** [softwarespartan/IB4m#34]
Hi Abel,

I experience a really annoying problem and slowly I’m growing desperate.

I’m using your IB4m and it works great for me so far. It works fine on my Mac it also works fine on my PC with windows 7 but I can not make it work compiled on another PC running windows 10.
(I'm deploying my ready strategies on a PC that does not have Matlab installed on it; I'm doing so successfully for other brokers. A difference with IB4m is the use of an external .jar file. So this might be part of the problem. The deployed version is finding the .jar file though since it is utilizing it to connect to the gateway.)
The computer connects to the gateway and sends all requests fine and I see also in the API messages  that it sends my requests to the IB server and that the server replies as it should.
For example when I request an account summary I see the requested data in the messages BUT somehow the data never makes it into the FIFO buffer.
First I thought I just would have to wait a little longer but no matter how long I wait the buffer remains empty (buf.isEmpty = true).
Running the same code on one of my other computers works without problems.

If you have an idea what might be wrong I’d be extremely grateful!

**Comment by softwarespartan** [comment]
Apologies for delay

Do you have he Trading Toolbox installed on the Windows box by chance?

This often happens because the trading toolbox has a conflicting jar file that gets automatically added the the static Java path at install.

**Comment by softwarespartan** [comment]
Is same version of matlab on both windows setups?

**Comment by Despair2000** [comment]
Can this problem maybe be caused by a path that was not set correctly?

**Comment by Despair2000** [comment]
External jar files are not added to the runtime while compiling, you have to copy them to the machine you deploy the application to and specify the path in the javaclasspath.txt. This works correctly I'm 99% sure. If the jar file was not accessible I could not call any functions from it (like for example connect to the gateway) or am I wrong?

I sadly have no access to a windows 10 PC with matlab on and the laptop I run it on is too weak to install matlab on it.

I read yesterday night that if a function is used in a callback as string or with feval then you have to specify this functions for the compiler to include. I wondered if this might be part of the problem but the whole callback with listener is implemented in the "initBuffer" java-function. Puh I really do not know what to do about this. :-(

**Comment by Despair2000** [comment]
To your idea with Trading Toolbox (I forgot to comment that), I don't have Trading Toolbox installed. Not on the windows 7 machine I'm compiling with and not on the windows 10 machine (obviously since it has no matlab installed).
I just had a look which toolboxes are installed on the PC I'm compiling with and the only two toolboxes that I can imagine could conflict with TWS are the database toolbox and the data audition toolbox. Do you have any experience with one of those causing problems?

**Comment by Despair2000** [comment]
I now uninstalled several toolboxes but this doesn't change the runtime that is installed along with the app. Obviously the compiler doesn't include unused toolboxes.
I also contacted mathwork support with the problem but they say they can't help me because a third-party software (IB4m) is involved in the problem. :-S
I somehow lack the knowledge that is required to debug this issue. To be honest I have no clue how exactly the gateway is communicating with the app in detail.

**Comment by softwarespartan** [comment]
It is nothing to do with the gateway.  IB4m works just fine with the gateway.

If you’re going to use the java compiler you might as well use IB API directly in java.  If you use complicated MATLAB functions then just compile them to java using the matlab compiler to java and then call them in your IB java program.  

This way you’re not taking a java API into MATLAB (i.e. IB4m) just to compile it back to Java using their very complicated tools and runtime. 

I don’t have the compiler so very difficult to debug.  my sense is that if the Win10 machine can’t even handle install matlab then probably not much hardcore mathematics in the trading algorithm.  This means probably easy to use IB java api directly and get rid of matlab (just guessing though).

-abel

**Comment by Despair2000** [comment]
I don't use the java compiler but the usual matlab compiler.

You are of course right, having the whole app written in java would solve this issue but this is no option for me since I have never worked with java and have no knowledge about it. :-S

I also agree that what I'm doing is a little bit back and forth but it works for me very well with algos i wrote for other brokers (which go directly via a web API and don't use java).

On the windows 10 machine it is more an issue of lacking capacity than lacking computational power. It has only a 32GB HDD which is already more than full with just windows installed (don't get me started) and almost all apps are running from flash drives and similar. Anyway it would be (with use of an external HDD) possible to install matlab on it but there are several reasons why I don't want to do so. This is a computer that I use at work and has the advantage of very fast, stable internet and it is running 24/7. This is of course nice for algo-trading. So I develop my algos at home (living outside town with unstable internet), compile them when they are ready and run them in the background on my work PC. This works great so far but it would look really strange if I would start installing matlab on this work PC - you understand.

Now a question that probably is pretty stupid, but I desperate enough to make you laugh. ;-) Does a computer need to have java installed to run IB4m?
I still have the feeling that it is something simple that is missing. Just like a PATH not set correctly or similar. But it can't be as simple as the app does not find the jar file. This problem I had before. If the jar-file is not found just trying to connect to the gateway caused several errors. Then I include a javaclasspath.txt in the folder of the deployed up containing the full path to the jar-file. This made it work and now I can call functions from the jar-file but somehow my app doesn't catch the replies from the gateway.

**Comment by Despair2000** [comment]
I now bought a laptop that I'm going to install in a closet at work. On this one I will have Matlab installed so I don't have to compile my apps and all hopefully goes fine and I can forget this annoying bug.
Thanks for your help anyway and thanks for sharing a so wonderful bit of software like IB4m!
