### ISSUE TITLE
Indicators in the studie folder

### ISSUE THREAD

**Issue by Despair2000** [softwarespartan/IB4m#35]
I now saw there is a folder called +Studies where you have code for several indicators. This might become handy.
Can you maybe give an example how to call this functions, for example the MACD?

**Comment by TukanKolor** [comment]
Despair,

Hey the way I am doing this is first getting the historical data over the time period.  There are examples of how to get the open, close, etc. included.  Once you have that the File Exchange has some good MATLAB files for Indicators.  I have one script that includes 21 different indicators.  I apply that script to the historical data and use the output to determine trades. Hopefully that helps.

-TukanKolor

**Comment by Despair2000** [comment]
Hi TukanKolor,

Thank you for your advice but I don't have any problems to calculate indicators. I just found the files in the +Studies folder and was wondering how to call these functions but this is no real problem. I was just curious. :-)
