### ISSUE TITLE
Possible to expose the events for "market rules"?

### ISSUE THREAD

**Issue by Benvaulter** [softwarespartan/IB4m#37]
Hi there,

any chance to expose the "market rule" events? I am trying to retrieve the minimum price variation for a given contract. The process to do this is to first request contract details and extract the "market rule id" and then insert this market rule id into another function called "reqMktRule" (https://interactivebrokers.github.io/tws-api/minimum_increment.html). Since no event is set up for this method, I am not able to fetch the data at this time. Would be great - many thanks in advance!

**Comment by softwarespartan** [comment]
MarketRules have been added with sample in the example folder

**Comment by softwarespartan** [comment]
No problem.  

Let me know if you need anything additional.  

Re: contract details, that’s fairly common workflow for IB API.  For example, options and futures require contract details to make appropriate market data call etc.  

Cheers
