### ISSUE TITLE
Requesting open orders when there are none makes IB4m freeze

### ISSUE THREAD

**Issue by Despair2000** [softwarespartan/IB4m#45]
Hi Abel,

I noticed today that IB4m freezes if you try to request open orders when there are none.
If there are open orders everything works as it should though.

Somehow it seems that it's always me who finds the bugs. Sorry for that. :-S

Cheers

**Comment by softwarespartan** [comment]
trying to repro but I don't get any errors or freeze.  In the IB4m docs folder there is example which I am using as reference.  Does this example work for you?  Or are you requesting open orders some other way, etc?  Just trying to figure out what the difference could be.

**Comment by Despair2000** [comment]
This is funny. Let me compare the example code and mine...
