### ISSUE TITLE
Out of memory error: Java heap space

### ISSUE THREAD

**Issue by Despair2000** [softwarespartan/IB4m#50]
It now happened to me a few times that matlab becomes unresponsive with this java heap space error. It always happens after I downloaded a lot of historical data.

Is this my code or IB4m that makes something strange?

**Comment by softwarespartan** [comment]
did you update java heap size for Matlab at launch?

https://www.mathworks.com/matlabcentral/answers/108738-how-do-i-increase-java-heap-size-to-greater-than-4-gb <https://www.mathworks.com/matlabcentral/answers/108738-how-do-i-increase-java-heap-size-to-greater-than-4-gb>

**Comment by Despair2000** [comment]
I just googled it and found that (should have done so before writing here). I will ramp up the size and try again.

Thanks!

**Comment by softwarespartan** [comment]
No worries, let me know if that works for you

**Comment by Despair2000** [comment]
I doubled the heap size and the error vanished.

Thanks!
