### ISSUE TITLE
keepUpToDate

### ISSUE THREAD

**Issue by Despair2000** [softwarespartan/IB4m#51]
There is a fairly new function when issuing a historical data request. If you set the keepUpToDate flag one should receive realtime updates of the requested data.

This seems to be useful but I wonder if it is usable with IB4m? If I understand it right the updates should trigger a historicDataUpdate event and these don't exist in IB4m or am I wrong?

**Comment by softwarespartan** [comment]
yes, that’s is roughly correct BUT …

Currently under the hood IB4m aggregates all data associated with a particular historical data request (unique via id) while waiting for historicalDataEnd API call which signals the conclusion of the server response.

If use the new flag, historical data call will aggregate forever.  

I see little need for this and just request real time bars. 

Not that Interactive Brokers asked me, but I def have to question some of their recent API updates.  

-abel

**Comment by Despair2000** [comment]
I'm with you on that. I already solved the situation with a separate realtime bar request like you also suggest. This seems to work fine. :-)
