### ISSUE TITLE
Fundamental data

### ISSUE THREAD

**Issue by Despair2000** [softwarespartan/IB4m#61]
Hi Abel,

It would be really awesome if you could take the time to expose the fundamental data event so we can use this function also with IB4m.
And if it doesn't make too much work, activating the financial advisor functionality would be also highly appreciated.

Thanks in advance!

**Comment by softwarespartan** [comment]
Ok, I’ll have a look

**Comment by softwarespartan** [comment]
@Despair2000 

Pushed updates today for fundamentalData and receiveFA API calls.

Let me know if find any bugs or need anything additional.
