### ISSUE TITLE
javaaddpath issue

### ISSUE THREAD

**Issue by turt8796** [softwarespartan/IB4m#78]
I am unable to get the javaaddpath function to work properly. It says I have an invalid file or directory when it applies to the file TWS.jar. Is there a problem with the .jar file or with setting up java for matlab?

**Comment by softwarespartan** [comment]
Not sure what "it" is.  Would likely be more helpful if you just post the actual error message.  There is no problem with the Jar file or java setup in MATLAB.    

What is the path to your jar file?  What do you get when you `ls` that path in your MATLAB command window?

**Comment by purchagent** [comment]
The jar file is now named TWS973
Either rename the file or change the "javaaddpath(fullfile(pwd,'Jar','TWS.jar'))" command to the new name
