### ISSUE TITLE
which api am i running

### ISSUE THREAD

**Issue by ciaoitaly** [softwarespartan/IB4m#86]
Hi is there an easy way to know if my ib4m uses 9.72 or 9.73 api? I see in Jar folder that file is TWS.jar but it was changed 4 months ago so im confused. my goal is to create conditions order so i need 9.73 i assume?

**Comment by softwarespartan** [comment]
You should see TWS973.jar on the git master branch.  Can you confirm you're on master?

**Comment by ciaoitaly** [comment]
In Jar folder, I see TWS.jar

**Comment by ciaoitaly** [comment]
What do you mean by "Can you confirm you're on master?"? I dont understand

**Comment by ciaoitaly** [comment]
Ok I think I was running old IB4m. I just updated to new one but it gets me an error when I run same code. When I create contract using 
contract = com.ib.client.Contract();
contract.m_secType = 'FUT';

No public field m_secType exists for class com.ib.client.Contract.

Do you know why I am getting this error with new IB4m? 

THanks so much !!!

**Comment by softwarespartan** [comment]
There were some IB updates in the API in +973.  

Checkout the IB API docs for defining contracts etc and I’ve also included some updated examples in the IB4m/docs folder

**Comment by softwarespartan** [comment]
For example, updated (+9.73) contract definition below

```
contract = com.ib.client.Contract();
contract.symbol('SPY')
contract.exchange('SMART');
contract.primaryExch('ISLAND');
contract.currency('USD');
contract.secType('STK');
``` 

See IB API docs here: http://interactivebrokers.github.io/tws-api/basic_contracts.html

**Comment by ciaoitaly** [comment]
Thanks much Abel !
