### ISSUE TITLE
MarketDataExample

### ISSUE THREAD

**Issue by dakr001** [softwarespartan/IB4m#91]
Hi Abel, Despair2000;

Tried the MarketDataExample in the depository but it looks like it needs an update. Got the error below:

Unrecognized function or variable 'm_exchange'.
Error in MarketDataExample (line 191)
map.put(reqId,contract.m_exchange);

More importantly could I get some tips on the code to run a callback function whenever there a market data event?

The example you have simply dumps data from databuf immediately after the subscription request.

I have been reading on the Matlab Event and Listener concepts but not sure if this is compatible with IB4m. The Matlab doc says to create a handle request for the notification and listener. Can I get some help please...

Below is what I think I should do:

classdef MyClass < handle 
   events 
      MarketDataEvents
   end
   ...
   methods
      function triggerEvent(obj)
         ...
         notify(obj,'MarketDataEvents');
      end
   end
end

function lh=createListener(src)
lh=addlistener(src, 'MarketDataEvents', @handlemarketevent)
end

function handlemarketevent
  % Submit order
  ...
end

obj=MyClass;

**Comment by softwarespartan** [comment]
@dakr001 can you make sure you're on the main branch.  The MarketData example should have contract defined as follows
```
contract = com.ib.client.Contract();
contract.symbol('SPY')
contract.exchange('SMART');
contract.primaryExch('ISLAND');
contract.currency('USD');
contract.secType('STK');
```

note the changes in syntax for API ver +9.73

**Comment by softwarespartan** [comment]
Regarding callbacks, not sure what you're looking for specifically.  The IB4m src has many examples.  Most of the examples put the event in a buffer for processing or print to screen but that's pretty generic.  There are no limitations -- just specify whatever callback function you want.  Also check out +TWS/NextOrderId.m for class based example of creating objects that respond to events.  Let me know if something more specific

**Comment by dakr001** [comment]
@softwarespartan Thank you for the quick reply.

Essentially what I'm trying to achieve is update order parameters (stop loss and take profit prices) if the ask/bid prices changes.

At the moment I run an infinite loop to check the ask/bid prices continuously and update the order parameters accordingly. Rather than checking the ask/bid price continuously, I would like for the parameter update to be triggered by market data events as they arrive.

Not sure if I understood you correctly. 

- The MarketDataExample does a single dump from databuf immediately after the subscription request.

- The NextOrderIdExample does a single get of the next order id

What I need is to run a callback function every time there is an update event to the price.

Thank you so much.


sds

**Comment by softwarespartan** [comment]
No problem — happy to help
