### ISSUE TITLE
Request fundamental data

### ISSUE THREAD

**Issue by mselser95** [softwarespartan/IB4m#95]
Is there an example or documentation to get the fundamentals of a ticker? a simple example would be very much appreciated.

Thank you!

**Comment by Despair2000** [comment]
Here you have my function to retrieve fundamental data. It returns the requested data in XML-format:

`function [data] = getFundamentalData(reqID,contract,reportType)
% 'ReportsFinSummary'     -	Financial summary
% 'ReportsOwnership'      - Company's ownership (Can be large in size)
% 'ReportSnapshot' 	      - Company's financial overview
% 'ReportsFinStatements'  - Financial Statements
% 'RESC'	              - Analyst Estimates  
% 'CalendarReport'	      - Company's calendar

global session

% create local buffer for account summary events 
[buf, lh] = TWS.initBufferForEvent(TWS.Events.FUNDAMENTALDATA);

reqFundamentalData(session.eClientSocket,reqID,contract,reportType,[])
pause(3)

if ~isEmpty(buf)
    data = collection2cell(buf);
else
    data = [];
end`

The documentation you find here:

**Comment by mselser95** [comment]
thank you for your help. I used your function but i'm getting an error, same as in the get historical data example.

this is my code:

`function ib_test()`
`% initialize session with TWS`
`session = TWS.Session.getInstance();`
`% connect to TWS`
`session.eClientSocket.eConnect('127.0.0.1',7496,0);
`% create an empty stock contract`
`contract = com.tws.ContractFactory.GenericStockContract('FB');`
`data  = getFundamentalData(session,8001,contract,'ReportsFinSummary')`
`end`

with your function (the only change I made was to pass session as an argument).

`function [data] = getFundamentalData(session, reqID,contract,reportType)`
`    % 'ReportsFinSummary' - Financial summary`
`    % 'ReportsOwnership' - Company's ownership (Can be large in size)`
`    % 'ReportSnapshot' - Company's financial overview`
`    % 'ReportsFinStatements' - Financial Statements`
`    % 'RESC' - Analyst Estimates`
`    % 'CalendarReport' - Company's calendar`
`    % create local buffer for fundamental data events`
`    [buf, lh] = TWS.initBufferForEvent(TWS.Events.FUNDAMENTALDATA);`
`    reqFundamentalData(session.eClientSocket,reqID,contract,reportType,[])`
`    pause(3)`
`    if ~isEmpty(buf)`
`        data = collection2cell(buf);`
`    else`
`        data = [];`
`    end`
`end`

This is the error I get:

'8001 321 Error validating request:-'bR' : cause - Please enter a valid security type'

Any ideas?

**Comment by softwarespartan** [comment]
be sure to checkout updated docs for +9.73 contracts etc [link](http://interactivebrokers.github.io/tws-api/contracts.html)

Example
```
contract = com.ib.client.Contract();
contract.symbol('SPY')
contract.exchange('SMART');
contract.primaryExch('ISLAND');
contract.currency('USD');
contract.secType('STK');
```

**Comment by mselser95** [comment]
Great. Thank you very much.
