### ISSUE TITLE
-1 507 Bad Message Length null

### ISSUE THREAD

**Issue by llagoudis** [softwarespartan/IB4m#98]
Hi, 

I am using a demo IB account TWS API 979.01 OS Win10 x64 amd MatlabR2019a. 

At TWS 'Enable ActiveX and Socket Client' is enable
Trusted IPs created a new at 127.0.0.1

I just get started with IB connection and I have some difficulties to get connection. 

`clc;
clear all;
addpath(path,pwd);  
addpath(path,fullfile(pwd,'docs'))
javaaddpath(fullfile(pwd,'Jar','TWS973.jar'));

AccountSummaryExample`

I am getting this error message : 

> notification listener has been removed
> added interface method: TWSNotification
> notification listener has been added
> -1 507 Bad Message Length null
> 
> Error using AccountSummaryExample (line 56)
> Java exception occurred:
> org.apache.commons.collections.BufferUnderflowException: The buffer is already empty
> 
> 	at org.apache.commons.collections.buffer.BoundedFifoBuffer.get(BoundedFifoBuffer.java:261)
> 

Could you please advice what I am doing wrong? 

Thanks

**Comment by softwarespartan** [comment]
Thanks for opening an issue.  This is just the java way to say "buffer was empty".  When`buf.size` is zero (i.e. empty) and if call `buf.get()` on empty `buf`, then java throws exception.  Probably just need to wait longer for response from TWS server.  But, I am not totally sure how account summary works for demo accounts.

**Comment by llagoudis** [comment]
Thank you for your help. Why I am getting empty buffer? 
I have run a few examples from the docs library and I am facing the error 
`1 507 Bad Message Length null`

In addition, why there are different contract configurations in docs vs examples
docs : contract.symbol('IBM');
examples : contract.m_symbol='IBM';

**Comment by softwarespartan** [comment]
Empyt `buf` just means no events have been received from TWS.  Depending on your internet speed, geography, etc, might take longer to get response from TWS servers. 

Are you sure that you're adding the jar file that comes with IB4m? Also there is conflict with IB jar that comes with the Matlab Trading Toolbox so be sure not to have that installed. 

I'm a bit delinquent in updating the examples for the +973 API changes.  Docs should be up to date though.

Official IB docs are updated and can be used directly.

http://interactivebrokers.github.io/tws-api/basic_contracts.html

Not sure on bad msg length.  I have never tested with demo account.

**Comment by llagoudis** [comment]
Hi,

I installed Trading Toolbox for MatlabR2019a. Where can I find this Java jar file? Do I need to delete it?

Jar file is added into path I have later on saved. see picture below

[cid:a0b37a7f-fe01-450e-9dc6-e24514079303]
________________________________

**Comment by softwarespartan** [comment]
I am not exactly sure where Matlab puts the Trading Toolbox jar (you could use Terminal to `find` it in the Applications dir for 2019a).  Long story short, if want to use IB4m then need to uninstall the trading toolbox to stop the conflicting jar file from getting added to the class loader path.  I realize it's a bit obnoxious to uninstall the toolbox.

**Comment by llagoudis** [comment]
Hi,

There many examples on the docs folder but what I am looking for is an end to end example like check portfolio positions and submit an order when a condition is met and then repeat the same check in 1 hour.

Regards,

Loukas Lagoudis
llagoudis@hotmail.co.uk
UK : +44 (0) 7935854931
CY : + 357 99842323

________________________________

**Comment by softwarespartan** [comment]
There are examples for both account updates and portfolio updates in the docs folder.  Also, be sure to checkout the IB API docs  

http://interactivebrokers.github.io/tws-api/account_portfolio.html

And, Matlab has timer callbacks as well

https://www.mathworks.com/help/matlab/matlab_prog/timer-callback-functions.html

p.s. since this question/issue is not related to " Bad Message Length null", should probably open new/separate issue.  Im going to close this issue but feel free to respond if you think topic is better discussed on this thread.
